collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.110337104415521
  brandStrength: 0.101485057733953
  rhythmicContrast: 0.5466326207388192
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  lightness: 0.6654555955901742
typography_spectrum: 0
layout_spectrum: 1
name: Sports Creative Taavetti Alin
